export const POPOVER_TYPE = {
    CONTEXT_MENU: 'CONTEXT_MENU',
    PLAIN: 'PLAIN',
    RICH: 'RICH',
    TEXT_INPUT_PICKER: 'TEXT_INPUT_PICKER',
    TOOLTIP: 'TOOLTIP'
} as const

export const POPOVER_CONTENT_POSITION = {
    HORIZONTAL_END: 'HORIZONTAL_END',
    HORIZONTAL_START: 'HORIZONTAL_START',
    VERTICAL_END: 'VERTICAL_END',
    VERTICAL_START: 'VERTICAL_START'
} as const
