/** @type {import('tailwindcss').Config} */
module.exports = {
        // NOTE: Update this to include the paths to all files that contain Nativewind classes.
        darkMode: 'class',
        content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
        presets: [require('nativewind/preset')],
        theme: {
                extend: {}
        },
        plugins: [],
        safelist: [
                'font-medium',
                'font-mono',
                'font-normal',
                'font-sans',
                'not-italic',
                'rounded-2xl',
                'rounded-3xl',
                'rounded-b-2xl',
                'rounded-b-3xl',
                'rounded-b-full',
                'rounded-b-lg',
                'rounded-b-md',
                'rounded-b-none',
                'rounded-b-sm',
                'rounded-b-xl',
                'rounded-full',
                'rounded-l-2xl',
                'rounded-l-3xl',
                'rounded-l-full',
                'rounded-l-lg',
                'rounded-l-md',
                'rounded-l-none',
                'rounded-l-sm',
                'rounded-l-xl',
                'rounded-lg',
                'rounded-md',
                'rounded-none',
                'rounded-r-2xl',
                'rounded-r-3xl',
                'rounded-r-full',
                'rounded-r-lg',
                'rounded-r-md',
                'rounded-r-none',
                'rounded-r-sm',
                'rounded-r-xl',
                'rounded-sm',
                'rounded-t-2xl',
                'rounded-t-3xl',
                'rounded-t-full',
                'rounded-t-lg',
                'rounded-t-md',
                'rounded-t-none',
                'rounded-t-sm',
                'rounded-t-xl',
                'rounded-xl',
                'text-2xl',
                'text-3xl',
                'text-4xl',
                'text-5xl',
                'text-6xl',
                'text-base',
                'text-lg',
                'text-sm',
                'text-xl',
                'text-xs',
                'tracking-normal',
                'tracking-tight',
                'tracking-wide',
                'tracking-wider',
                'tracking-widest'
        ]
}
