/** @type {import('tailwindcss').Config} */
module.exports = {
        // NOTE: Update this to include the paths to all files that contain Nativewind classes.
        darkMode: 'class',
        content: ['./src/**/*.{js,jsx,ts,tsx}'],
        presets: [require('nativewind/preset')],
        theme: {extend: {}},
        plugins: [],
        safelist: [
                'color-[--color-on-surface]',
                'font-[family-name:var(--font-family)]',
                'font-normal',
                'font-semibold',
                'leading-[1.25rem]',
                'leading-[1.5rem]',
                'leading-[1.75rem]',
                'leading-[1rem]',
                'leading-[2.25rem]',
                'leading-[2.5rem]',
                'leading-[2.75rem]',
                'leading-[2rem]',
                'leading-[3.25rem]',
                'leading-[4rem]',
                'not-italic',
                'rounded-[0.125rem]',
                'rounded-[0.25rem]',
                'rounded-[0.5rem]',
                'rounded-[0.75rem]',
                'rounded-[1.75rem]',
                'rounded-[1rem]',
                'rounded-b-[0.125rem]',
                'rounded-b-[0.25rem]',
                'rounded-b-[0.5rem]',
                'rounded-b-[0.75rem]',
                'rounded-b-[1.75rem]',
                'rounded-b-[1rem]',
                'rounded-b-full',
                'rounded-full',
                'rounded-l-[0.125rem]',
                'rounded-l-[0.25rem]',
                'rounded-l-[0.5rem]',
                'rounded-l-[0.75rem]',
                'rounded-l-[1.75rem]',
                'rounded-l-[1rem]',
                'rounded-l-full',
                'rounded-r-[0.125rem]',
                'rounded-r-[0.25rem]',
                'rounded-r-[0.5rem]',
                'rounded-r-[0.75rem]',
                'rounded-r-[1.75rem]',
                'rounded-r-[1rem]',
                'rounded-r-full',
                'rounded-t-[0.125rem]',
                'rounded-t-[0.25rem]',
                'rounded-t-[0.5rem]',
                'rounded-t-[0.75rem]',
                'rounded-t-[1.75rem]',
                'rounded-t-[1rem]',
                'rounded-t-full',
                'text-[0.6875rem]',
                'text-[0.75rem]',
                'text-[0.875rem]',
                'text-[1.375rem]',
                'text-[1.5rem]',
                'text-[1.75rem]',
                'text-[1rem]',
                'text-[2.25rem]',
                'text-[2.8125rem]',
                'text-[2rem]',
                'text-[3.5625rem]',
                'tracking-normal',
                'tracking-tight',
                'tracking-wide',
                'tracking-wider',
                'tracking-widest'
        ]
}
