import type {Contrast} from '../color'
import type {SCHEME} from '../scheme'
import type {PALETTE} from './palette.enum'

export type PaletteType = (typeof PALETTE)[keyof typeof PALETTE]
export type ColorRole =
	| 'background'
	| 'error'
	| 'errorContainer'
	| 'inverseOnSurface'
	| 'inversePrimary'
	| 'inverseSurface'
	| 'neutralVariant100'
	| 'neutralVariant99'
	| 'onBackground'
	| 'onError'
	| 'onErrorContainer'
	| 'onPrimary'
	| 'onPrimaryContainer'
	| 'onPrimaryFixed'
	| 'onPrimaryFixedVariant'
	| 'onSecondary'
	| 'onSecondaryContainer'
	| 'onSecondaryFixed'
	| 'onSecondaryFixedVariant'
	| 'onSurface'
	| 'onSurfaceVariant'
	| 'onTertiary'
	| 'onTertiaryContainer'
	| 'onTertiaryFixed'
	| 'onTertiaryFixedVariant'
	| 'outline'
	| 'outlineVariant'
	| 'primary'
	| 'primaryContainer'
	| 'primaryFixed'
	| 'primaryFixedDim'
	| 'scrim'
	| 'secondary'
	| 'secondaryContainer'
	| 'secondaryFixed'
	| 'secondaryFixedDim'
	| 'shadow'
	| 'surface'
	| 'surfaceBright'
	| 'surfaceContainer'
	| 'surfaceContainerHigh'
	| 'surfaceContainerHighest'
	| 'surfaceContainerLow'
	| 'surfaceContainerLowest'
	| 'surfaceDim'
	| 'surfaceTint'
	| 'surfaceVariant'
	| 'tertiary'
	| 'tertiaryContainer'
	| 'tertiaryFixed'
	| 'tertiaryFixedDim'

export type CoreColor = 'primary' | 'secondary' | 'tertiary' | 'error' | 'neutral' | 'neutralVariant'
export interface Palette {
	[SCHEME.DARK]: Record<Contrast, Record<ColorRole, string>>
	[SCHEME.LIGHT]: Record<Contrast, Record<ColorRole, string>>
	coreColor: Record<CoreColor, string | undefined>
	seed: string
}
