import {SHAPE} from './shape.enum'
import type {Shape} from './shape.interface'

const SHAPE_SIZE = {
	[SHAPE.X_LARGE]: 28,
	[SHAPE.X_SMALL]: 4,
	[SHAPE.FULL]: 9999,
	[SHAPE.LARGE]: 16,
	[SHAPE.MEDIUM]: 12,
	[SHAPE.NONE]: 0,
	[SHAPE.SMALL]: 8,
	[SHAPE.TINY_SMALL]: 2
}

export const createShape = (): Shape => ({
	size: SHAPE_SIZE,
	[SHAPE.TINY_SMALL]: {
		bottomLeft: SHAPE_SIZE[SHAPE.TINY_SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.TINY_SMALL],
		topLeft: SHAPE_SIZE[SHAPE.TINY_SMALL],
		topRight: SHAPE_SIZE[SHAPE.TINY_SMALL]
	},
	[SHAPE.TINY_SMALL_BOTTOM]: {
		bottomLeft: SHAPE_SIZE[SHAPE.TINY_SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.TINY_SMALL],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.TINY_SMALL_END]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.TINY_SMALL],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.TINY_SMALL]
	},
	[SHAPE.TINY_SMALL_START]: {
		bottomLeft: SHAPE_SIZE[SHAPE.TINY_SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.TINY_SMALL],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.TINY_SMALL_TOP]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.TINY_SMALL],
		topRight: SHAPE_SIZE[SHAPE.TINY_SMALL]
	},
	[SHAPE.X_SMALL]: {
		bottomLeft: SHAPE_SIZE[SHAPE.X_SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.X_SMALL],
		topLeft: SHAPE_SIZE[SHAPE.X_SMALL],
		topRight: SHAPE_SIZE[SHAPE.X_SMALL]
	},
	[SHAPE.X_SMALL_BOTTOM]: {
		bottomLeft: SHAPE_SIZE[SHAPE.X_SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.X_SMALL],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.X_SMALL_END]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.X_SMALL],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.X_SMALL]
	},
	[SHAPE.X_SMALL_START]: {
		bottomLeft: SHAPE_SIZE[SHAPE.X_SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.X_SMALL],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.X_SMALL_TOP]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.X_SMALL],
		topRight: SHAPE_SIZE[SHAPE.X_SMALL]
	},
	[SHAPE.SMALL]: {
		bottomLeft: SHAPE_SIZE[SHAPE.SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.SMALL],
		topLeft: SHAPE_SIZE[SHAPE.SMALL],
		topRight: SHAPE_SIZE[SHAPE.SMALL]
	},
	[SHAPE.SMALL_BOTTOM]: {
		bottomLeft: SHAPE_SIZE[SHAPE.SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.SMALL],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.SMALL_END]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.SMALL],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.SMALL]
	},
	[SHAPE.SMALL_START]: {
		bottomLeft: SHAPE_SIZE[SHAPE.SMALL],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.SMALL],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.SMALL_TOP]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.SMALL],
		topRight: SHAPE_SIZE[SHAPE.SMALL]
	},
	[SHAPE.MEDIUM]: {
		bottomLeft: SHAPE_SIZE[SHAPE.MEDIUM],
		bottomRight: SHAPE_SIZE[SHAPE.MEDIUM],
		topLeft: SHAPE_SIZE[SHAPE.MEDIUM],
		topRight: SHAPE_SIZE[SHAPE.MEDIUM]
	},
	[SHAPE.MEDIUM_BOTTOM]: {
		bottomLeft: SHAPE_SIZE[SHAPE.MEDIUM],
		bottomRight: SHAPE_SIZE[SHAPE.MEDIUM],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.MEDIUM_END]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.MEDIUM],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.MEDIUM]
	},
	[SHAPE.MEDIUM_START]: {
		bottomLeft: SHAPE_SIZE[SHAPE.MEDIUM],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.MEDIUM],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.MEDIUM_TOP]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.MEDIUM],
		topRight: SHAPE_SIZE[SHAPE.MEDIUM]
	},
	[SHAPE.LARGE]: {
		bottomLeft: SHAPE_SIZE[SHAPE.LARGE],
		bottomRight: SHAPE_SIZE[SHAPE.LARGE],
		topLeft: SHAPE_SIZE[SHAPE.LARGE],
		topRight: SHAPE_SIZE[SHAPE.LARGE]
	},
	[SHAPE.LARGE_BOTTOM]: {
		bottomLeft: SHAPE_SIZE[SHAPE.LARGE],
		bottomRight: SHAPE_SIZE[SHAPE.LARGE],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.LARGE_END]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.LARGE],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.LARGE]
	},
	[SHAPE.LARGE_START]: {
		bottomLeft: SHAPE_SIZE[SHAPE.LARGE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.LARGE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.LARGE_TOP]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.LARGE],
		topRight: SHAPE_SIZE[SHAPE.LARGE]
	},
	[SHAPE.X_LARGE]: {
		bottomLeft: SHAPE_SIZE[SHAPE.X_LARGE],
		bottomRight: SHAPE_SIZE[SHAPE.X_LARGE],
		topLeft: SHAPE_SIZE[SHAPE.X_LARGE],
		topRight: SHAPE_SIZE[SHAPE.X_LARGE]
	},
	[SHAPE.X_LARGE_BOTTOM]: {
		bottomLeft: SHAPE_SIZE[SHAPE.X_LARGE],
		bottomRight: SHAPE_SIZE[SHAPE.X_LARGE],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.X_LARGE_END]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.X_LARGE],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.X_LARGE]
	},
	[SHAPE.X_LARGE_START]: {
		bottomLeft: SHAPE_SIZE[SHAPE.X_LARGE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.X_LARGE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.X_LARGE_TOP]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.X_LARGE],
		topRight: SHAPE_SIZE[SHAPE.X_LARGE]
	},
	[SHAPE.FULL]: {
		bottomLeft: SHAPE_SIZE[SHAPE.FULL],
		bottomRight: SHAPE_SIZE[SHAPE.FULL],
		topLeft: SHAPE_SIZE[SHAPE.FULL],
		topRight: SHAPE_SIZE[SHAPE.FULL]
	},
	[SHAPE.FULL_BOTTOM]: {
		bottomLeft: SHAPE_SIZE[SHAPE.FULL],
		bottomRight: SHAPE_SIZE[SHAPE.FULL],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.FULL_END]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.FULL],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.FULL]
	},
	[SHAPE.FULL_START]: {
		bottomLeft: SHAPE_SIZE[SHAPE.FULL],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.FULL],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	},
	[SHAPE.FULL_TOP]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.FULL],
		topRight: SHAPE_SIZE[SHAPE.FULL]
	},
	[SHAPE.NONE]: {
		bottomLeft: SHAPE_SIZE[SHAPE.NONE],
		bottomRight: SHAPE_SIZE[SHAPE.NONE],
		topLeft: SHAPE_SIZE[SHAPE.NONE],
		topRight: SHAPE_SIZE[SHAPE.NONE]
	}
})
