export const WINDOW_SIZE = {
	COMPACT: 'COMPACT',
	EXPANDED: 'EXPANDED',
	X_LARGE: 'X_LARGE',
	XX_LARGE: 'XX_LARGE',
	LARGE: 'LARGE',
	MEDIUM: 'MEDIUM'
} as const

export const UI_DENSITY = {
	COMPACT: 'COMPACT',
	COMFORTABLE: 'COMFORTABLE'
} as const

export const DENSITY_TYPE = {
	CONTROL: 'CONTROL',
	ICON: 'ICON',
	INLINE: 'INLINE',
	INSET: 'INSET',
	LAYOUT: 'LAYOUT',
	SPACING: 'SPACING'
} as const

export const LAYOUT_DENSITY = {
	NAVIGATION: 'NAVIGATION',
	SIDEBAR: 'SIDEBAR'
} as const

export const DENSITY_SIZE = {
	LARGE: 'LARGE',
	MEDIUM: 'MEDIUM',
	NONE: 'NONE',
	SMALL: 'SMALL',
	SNUG: 'SNUG',
	TIGHT: 'TIGHT',
	X_LARGE: 'X_LARGE',
	X_SMALL: 'X_SMALL',
	XX_LARGE: 'XX_LARGE'
} as const
