export const WINDOW_SIZE = {
	COMPACT: 'COMPACT',
	EXPANDED: 'EXPANDED',
	EXTRA_LARGE: 'EXTRA_LARGE',
	LARGE: 'LARGE',
	MEDIUM: 'MEDIUM'
} as const

export const UI_DENSITY = {
	COMPACT: 'COMPACT',
	COMFORTABLE: 'COMFORTABLE'
} as const

export const DENSITY_TYPE = {
	CONTROL: 'CONTROL',
	ICON: 'ICON',
	INLINE: 'INLINE',
	INSET: 'INSET',
	LAYOUT: 'LAYOUT',
	SPACING: 'SPACING'
} as const
