import {Platform} from 'react-native'
import {DENSITY_SIZE, LAYOUT_DENSITY, UI_DENSITY, WINDOW_SIZE} from './density.enum'
import type {Density, DensitySizeScale, Spacing, UIDensity, WindowSize} from './density.interface'

const SPACING = {
	[UI_DENSITY.COMPACT]: {
		[DENSITY_SIZE.LARGE]: 16,
		[DENSITY_SIZE.MEDIUM]: 12,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 8,
		[DENSITY_SIZE.SNUG]: 6,
		[DENSITY_SIZE.TIGHT]: 10,
		[DENSITY_SIZE.X_LARGE]: 24,
		[DENSITY_SIZE.X_SMALL]: 4,
		[DENSITY_SIZE.XX_LARGE]: 32,
		[DENSITY_SIZE.XX_SMALL]: 2
	},
	[UI_DENSITY.COMFORTABLE]: {
		[DENSITY_SIZE.LARGE]: 20,
		[DENSITY_SIZE.MEDIUM]: 16,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 12,
		[DENSITY_SIZE.SNUG]: 10,
		[DENSITY_SIZE.TIGHT]: 14,
		[DENSITY_SIZE.X_LARGE]: 28,
		[DENSITY_SIZE.X_SMALL]: 8,
		[DENSITY_SIZE.XX_LARGE]: 36,
		[DENSITY_SIZE.XX_SMALL]: 4
	}
}

const INSET = SPACING
const CONTROL = {
	[UI_DENSITY.COMPACT]: {
		[DENSITY_SIZE.LARGE]: 36,
		[DENSITY_SIZE.MEDIUM]: 32,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 28,
		[DENSITY_SIZE.X_LARGE]: 40,
		[DENSITY_SIZE.X_SMALL]: 24,
		[DENSITY_SIZE.XX_LARGE]: 48,
		[DENSITY_SIZE.XX_SMALL]: 22
	},
	[UI_DENSITY.COMFORTABLE]: {
		[DENSITY_SIZE.LARGE]: 48,
		[DENSITY_SIZE.MEDIUM]: 40,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 36,
		[DENSITY_SIZE.X_LARGE]: 56,
		[DENSITY_SIZE.X_SMALL]: 32,
		[DENSITY_SIZE.XX_LARGE]: 64,
		[DENSITY_SIZE.XX_SMALL]: 30
	}
}

const LAYOUT = {
	[UI_DENSITY.COMPACT]: {
		[DENSITY_SIZE.NONE]: 0,
		[LAYOUT_DENSITY.NAVIGATION]: 72,
		[LAYOUT_DENSITY.SIDEBAR]: 280
	},
	[UI_DENSITY.COMFORTABLE]: {
		[DENSITY_SIZE.NONE]: 0,
		[LAYOUT_DENSITY.NAVIGATION]: 80,
		[LAYOUT_DENSITY.SIDEBAR]: 320
	}
}

const ICON = {
	[UI_DENSITY.COMPACT]: {
		[DENSITY_SIZE.LARGE]: 20,
		[DENSITY_SIZE.MEDIUM]: 18,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 16,
		[DENSITY_SIZE.X_LARGE]: 24,
		[DENSITY_SIZE.X_SMALL]: 14,
		[DENSITY_SIZE.XX_LARGE]: 28,
		[DENSITY_SIZE.XX_SMALL]: 12
	},
	[UI_DENSITY.COMFORTABLE]: {
		[DENSITY_SIZE.LARGE]: 24,
		[DENSITY_SIZE.MEDIUM]: 20,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 18,
		[DENSITY_SIZE.X_LARGE]: 28,
		[DENSITY_SIZE.X_SMALL]: 16,
		[DENSITY_SIZE.XX_LARGE]: 32,
		[DENSITY_SIZE.XX_SMALL]: 14
	}
}

const INLINE = {
	[UI_DENSITY.COMPACT]: {
		[DENSITY_SIZE.LARGE]: 36,
		[DENSITY_SIZE.MEDIUM]: 32,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 28,
		[DENSITY_SIZE.X_LARGE]: 40,
		[DENSITY_SIZE.X_SMALL]: 24,
		[DENSITY_SIZE.XX_LARGE]: 48,
		[DENSITY_SIZE.XX_SMALL]: 22
	},
	[UI_DENSITY.COMFORTABLE]: {
		[DENSITY_SIZE.LARGE]: 48,
		[DENSITY_SIZE.MEDIUM]: 40,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 36,
		[DENSITY_SIZE.X_LARGE]: 56,
		[DENSITY_SIZE.X_SMALL]: 32,
		[DENSITY_SIZE.XX_LARGE]: 64,
		[DENSITY_SIZE.XX_SMALL]: 30
	}
}

const createMobileGap = (spacing: Spacing) => {
	const gap = {
		[WINDOW_SIZE.COMPACT]: spacing[DENSITY_SIZE.MEDIUM],
		[WINDOW_SIZE.EXPANDED]: spacing[DENSITY_SIZE.LARGE],
		[WINDOW_SIZE.X_LARGE]: spacing[DENSITY_SIZE.LARGE],
		[WINDOW_SIZE.XX_LARGE]: spacing[DENSITY_SIZE.LARGE],
		[WINDOW_SIZE.LARGE]: spacing[DENSITY_SIZE.LARGE],
		[WINDOW_SIZE.MEDIUM]: spacing[DENSITY_SIZE.LARGE]
	}

	return (windowSize: WindowSize) => gap[windowSize]
}

const densitySizeMapIconSize = (size: DensitySizeScale) => {
	const iconSize = {
		[DENSITY_SIZE.LARGE]: DENSITY_SIZE.MEDIUM,
		[DENSITY_SIZE.MEDIUM]: DENSITY_SIZE.SMALL,
		[DENSITY_SIZE.SMALL]: DENSITY_SIZE.X_SMALL,
		[DENSITY_SIZE.X_LARGE]: DENSITY_SIZE.LARGE,
		[DENSITY_SIZE.X_SMALL]: DENSITY_SIZE.X_SMALL,
		[DENSITY_SIZE.XX_LARGE]: DENSITY_SIZE.X_LARGE,
		[DENSITY_SIZE.XX_SMALL]: DENSITY_SIZE.XX_SMALL
	}

	return iconSize[size]
}

const densitySizeMapInlineSize = (size: DensitySizeScale) => {
	const inlineSize = {
		[DENSITY_SIZE.LARGE]: DENSITY_SIZE.MEDIUM,
		[DENSITY_SIZE.MEDIUM]: DENSITY_SIZE.SMALL,
		[DENSITY_SIZE.SMALL]: DENSITY_SIZE.X_SMALL,
		[DENSITY_SIZE.X_LARGE]: DENSITY_SIZE.MEDIUM,
		[DENSITY_SIZE.X_SMALL]: DENSITY_SIZE.X_SMALL,
		[DENSITY_SIZE.XX_LARGE]: DENSITY_SIZE.LARGE,
		[DENSITY_SIZE.XX_SMALL]: DENSITY_SIZE.XX_SMALL
	}

	return inlineSize[size]
}

const pxToRem =
	(basePX = 16) =>
	(px: number) =>
		px / basePX

const platformValue = (value: number) => {
	'worklet'

	return Platform.select<string | number>({default: value, web: `${pxToRem()(value)}rem`})
}

const createDensity = (density: UIDensity = UI_DENSITY.COMPACT): Density => ({
	control: CONTROL[density],
	icon: ICON[density],
	inline: INLINE[density],
	inset: INSET[density],
	layout: LAYOUT[density],
	spacing: SPACING[density]
})

const mobileGap = createMobileGap(SPACING[UI_DENSITY.COMFORTABLE])

export {platformValue, createDensity, mobileGap, densitySizeMapIconSize, densitySizeMapInlineSize}
