import {LAYOUT_DENSITY, DENSITY_SIZE, UI_DENSITY, WINDOW_SIZE} from './density.enum'
import type {Density, Spacing, UIDensity, WindowSize} from './density.interface'

const createMobileGap = (spacing: Spacing) => {
	const gap = {
		[WINDOW_SIZE.COMPACT]: spacing[DENSITY_SIZE.MEDIUM],
		[WINDOW_SIZE.EXPANDED]: spacing[DENSITY_SIZE.LARGE],
		[WINDOW_SIZE.X_LARGE]: spacing[DENSITY_SIZE.LARGE],
		[WINDOW_SIZE.XX_LARGE]: spacing[DENSITY_SIZE.LARGE],
		[WINDOW_SIZE.LARGE]: spacing[DENSITY_SIZE.LARGE],
		[WINDOW_SIZE.MEDIUM]: spacing[DENSITY_SIZE.LARGE]
	}

	return (windowSize: WindowSize) => gap[windowSize]
}

export const createDensity = (density: UIDensity = UI_DENSITY.COMPACT): Density => {
	const spacing = {
		[DENSITY_SIZE.LARGE]: 16,
		[DENSITY_SIZE.MEDIUM]: 12,
		[DENSITY_SIZE.NONE]: 0,
		[DENSITY_SIZE.SMALL]: 8,
		[DENSITY_SIZE.SNUG]: 6,
		[DENSITY_SIZE.TIGHT]: 10,
		[DENSITY_SIZE.X_LARGE]: 24,
		[DENSITY_SIZE.X_SMALL]: 4,
		[DENSITY_SIZE.XX_LARGE]: 32
	}

	const inset = {
		[UI_DENSITY.COMPACT]: {
			[DENSITY_SIZE.LARGE]: 16,
			[DENSITY_SIZE.MEDIUM]: 12,
			[DENSITY_SIZE.NONE]: 0,
			[DENSITY_SIZE.SMALL]: 8,
			[DENSITY_SIZE.X_LARGE]: 20,
			[DENSITY_SIZE.X_SMALL]: 4,
			[DENSITY_SIZE.XX_LARGE]: 24
		},
		[UI_DENSITY.COMFORTABLE]: {
			[DENSITY_SIZE.LARGE]: 20,
			[DENSITY_SIZE.MEDIUM]: 16,
			[DENSITY_SIZE.NONE]: 0,
			[DENSITY_SIZE.SMALL]: 12,
			[DENSITY_SIZE.X_LARGE]: 24,
			[DENSITY_SIZE.X_SMALL]: 8,
			[DENSITY_SIZE.XX_LARGE]: 28
		}
	}

	const control = {
		[UI_DENSITY.COMPACT]: {
			[DENSITY_SIZE.LARGE]: 36,
			[DENSITY_SIZE.MEDIUM]: 32,
			[DENSITY_SIZE.NONE]: 0,
			[DENSITY_SIZE.SMALL]: 28,
			[DENSITY_SIZE.X_LARGE]: 40,
			[DENSITY_SIZE.X_SMALL]: 24,
			[DENSITY_SIZE.XX_LARGE]: 48
		},
		[UI_DENSITY.COMFORTABLE]: {
			[DENSITY_SIZE.LARGE]: 48,
			[DENSITY_SIZE.MEDIUM]: 40,
			[DENSITY_SIZE.NONE]: 0,
			[DENSITY_SIZE.SMALL]: 36,
			[DENSITY_SIZE.X_LARGE]: 56,
			[DENSITY_SIZE.X_SMALL]: 32,
			[DENSITY_SIZE.XX_LARGE]: 64
		}
	}

	const layout = {
		[UI_DENSITY.COMPACT]: {
			[DENSITY_SIZE.NONE]: 0,
			[LAYOUT_DENSITY.NAVIGATION]: 72,
			[LAYOUT_DENSITY.SIDEBAR]: 280
		},
		[UI_DENSITY.COMFORTABLE]: {
			[DENSITY_SIZE.NONE]: 0,
			[LAYOUT_DENSITY.NAVIGATION]: 80,
			[LAYOUT_DENSITY.SIDEBAR]: 320
		}
	}

	const icon = {
		[UI_DENSITY.COMPACT]: {
			[DENSITY_SIZE.LARGE]: 20,
			[DENSITY_SIZE.MEDIUM]: 18,
			[DENSITY_SIZE.NONE]: 0,
			[DENSITY_SIZE.SMALL]: 16,
			[DENSITY_SIZE.X_LARGE]: 24,
			[DENSITY_SIZE.X_SMALL]: 14,
			[DENSITY_SIZE.XX_LARGE]: 28
		},
		[UI_DENSITY.COMFORTABLE]: {
			[DENSITY_SIZE.LARGE]: 24,
			[DENSITY_SIZE.MEDIUM]: 20,
			[DENSITY_SIZE.NONE]: 0,
			[DENSITY_SIZE.SMALL]: 18,
			[DENSITY_SIZE.X_LARGE]: 28,
			[DENSITY_SIZE.X_SMALL]: 16,
			[DENSITY_SIZE.XX_LARGE]: 32
		}
	}

	const inline = {
		[UI_DENSITY.COMPACT]: {
			[DENSITY_SIZE.LARGE]: 36,
			[DENSITY_SIZE.MEDIUM]: 32,
			[DENSITY_SIZE.NONE]: 0,
			[DENSITY_SIZE.SMALL]: 28,
			[DENSITY_SIZE.X_LARGE]: 40,
			[DENSITY_SIZE.X_SMALL]: 24,
			[DENSITY_SIZE.XX_LARGE]: 48
		},
		[UI_DENSITY.COMFORTABLE]: {
			[DENSITY_SIZE.LARGE]: 48,
			[DENSITY_SIZE.MEDIUM]: 40,
			[DENSITY_SIZE.NONE]: 0,
			[DENSITY_SIZE.SMALL]: 36,
			[DENSITY_SIZE.X_LARGE]: 56,
			[DENSITY_SIZE.X_SMALL]: 32,
			[DENSITY_SIZE.XX_LARGE]: 64
		}
	}

	return {
		spacing,
		inset: inset[density],
		control: control[density],
		icon: icon[density],
		layout: layout[density],
		inline: inline[density],
		mobileGap: createMobileGap(spacing)
	}
}
