import {SIZE} from '@bearei/theme-token'

export const ICON_BUTTON_SIZE = {
    [SIZE.EXTRA_LARGE]: SIZE.LARGE,
    [SIZE.EXTRA_SMALL]: SIZE.EXTRA_SMALL,
    [SIZE.LARGE]: SIZE.MEDIUM,
    [SIZE.MEDIUM]: SIZE.SMALL,
    [SIZE.SMALL]: SIZE.SMALL
}
