export const NAVIGATION_RAIL_ANIMATED = {
	NONE: 'NONE',
	COLLAPSE: 'COLLAPSE'
} as const

export const NAVIGATION_RAIL_TYPE = {
	SEGMENT: 'SEGMENT',
	BLOCK: 'BLOCK'
} as const

export const NAVIGATION_DESTINATION_POSITION = {
	TOP: 'TOP',
	CENTER: 'CENTER',
	BOTTOM: 'BOTTOM'
} as const
