export const LAYOUT_ANIMATED = {
	COLLAPSE_X: 'COLLAPSE_X',
	COLLAPSE_X_AND_FADE: 'COLLAPSE_X_AND_FADE',
	COLLAPSE_Y: 'COLLAPSE_Y',
	COLLAPSE_Y_AND_FADE: 'COLLAPSE_Y_AND_FADE',
	FADE: 'FADE',
	NONE: 'NONE',
	SCALE: 'SCALE'
} as const
