export const LAYOUT = {
	HORIZONTAL: 'HORIZONTAL',
	VERTICAL: 'VERTICAL'
} as const

export const DENSITY = {
	COMFORTABLE: 'COMFORTABLE',
	COMPACT: 'COMPACT',
	STANDARD: 'STANDARD'
} as const

export const DENSITY_SCALE = {
	COMFORTABLE: -1,
	COMPACT: -2,
	STANDARD: 0
} as const
